config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  get 'albums', to: 'albums#index'

  post 'albums', to: 'albums#create'

  get 'albums/:id', to: 'albums#show', as: :album

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    ALBUMS = {
    1 => { album_name: "Black Album", year: 1987, genre: "rock" },
    2 => { album_name: "White Album", year: 1965, genre: "classic rock" }
  }

  def index
    if params[:genre].blank?
      @albums = ALBUMS
    else
      @albums = ALBUMS.select do |id, album|
        album[:genre] == params[:genre]
      end
    end
  end

  def create
  end

  def show
    @album = ALBUMS[params[:id].to_i]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end

  def home
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/albums/index.html.erb
<h1>Albums</h1>

<form action="/albums" method="get">
  <input type="text" name="genre" placeholder="What genre do you like?">
  <input type="submit">
</form>

<ul>
  <% @albums.each do |id, album| %>
  <li>
    <%= link_to album[:album_name], album_path(id) %>
    (<%= album[:year]%>)
  </li>
  <% end %>
</ul>

app/views/albums/show.html.erb
<h1><%= @album [:album_name] %></h1>

<p>
  Saiu no ano de <%= @album[:year]%>
</p>

<p>Gênero: <strong> <%= @album[:genre] %></strong>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tests</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  <footer>
    Made in Sala 33
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "Home", root_path %>
  </footer>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<h1>Home Sweet Home!</h1>

<h2>Add an Album!</h2>

<form action="/albums" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="album_name" placeholder="Album Name">
  <input type="text" name="year" placeholder="Year">
  <input type="text" name="genre" placeholder="Genre">
  <input type="submit">
</form>